### ISSUE TITLE
When a user uploads an artwork, save all the neccessary fields

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/2019-level2#18]
When you upload an artwork, the form should let you include:

- image - that's being done seperately
- name of artwork
- description
- price
- hashtags

For reference, look at this old issue: https://github.com/girlcodeakl/girlcode2018-term4/issues/9

[ ] add an input for each of these to the form at `post.html`. (Don't worry about how it looks for now because the page is being redone.)
[ ] send the value from each input through to the server - JavaScript in `post.html`
[ ] on the server side, get each value and save it into the post object
[ ] in feed.html, display each of the values. Just get them on screen, don't worry about presentation because this page is being redone.

**Comment by jillGlass** [comment]
Form now includes name of artwork, description, price, hashtags inputs

**Comment by jillGlass** [comment]
added form fields and send values to server
